_target_: pytorch_lightning.Trainer

tpus: -1
gpus: 0
enable_checkpointing: true
strategy: dp
default_root_dir: ${current_experiment_dir}
progress_bar_refresh_rate: 1
enable_progress_bar: True
val_check_interval: 0.05
#limit_val_batches: 5
max_epochs: 1
log_every_n_steps: 1
precision: 32
num_sanity_val_steps: 2
auto_scale_batch_size: False

