defaults:
  - image_embedding_config: base-image-vi-transformer16.yaml
  - audio_embedding_config: base-audio-convformer.yaml
  - text_embedding_config: base-text-transformer.yaml
  - video_embedding_config: base-video-transformer.yaml
  - optimizer_config: adam.yaml
  - lr_scheduler_config: cosine_annealing.yaml

_target_: capit.models.systems.DumbusPrime

embedding_output_features: 512
logit_scale: 14.2857142857
name: base_dumbnet

#image_embedding_config:
#    _target_: capit.models.auto_builder.transformers.AutoDumbNet
#    embedding_output_features: 512
#
#audio_embedding_config:
#    _target_: capit.models.auto_builder.transformers.AutoDumbNet
#    embedding_output_features: 512
#
##text_embedding_config:
##    _target_: capit.models.auto_builder.transformers.AutoDumbNet
##    embedding_output_features: 512
#
#video_embedding_config:
#    _target_: capit.models.auto_builder.transformers.AutoDumbNet
#    embedding_output_features: 512