defaults:
  - optimizer_config: adam.yaml
  - lr_scheduler_config: cosine_annealing.yaml
  - image_embedding_config: dumbus_net.yaml
  - audio_embedding_config: dumbus_net.yaml
  - text_embedding_config: dumbus_net.yaml
  - video_embedding_config: dumbus_net.yaml

_target_: capit.models.systems.DumbusPrime

embedding_output_features: 512
logit_scale: 1.0

name: base_dumbnet