# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: ${wandb_project_name}
  offline: False # set True to store all logs only locally
  resume: allow # allow, True, False, must
  save_dir: ${current_experiment_dir}/
  log_model: all
  prefix: ""
  job_type: "train"
  group: ""
  tags: []
