defaults:
  - tali.yaml


dataloader_config:
  train_num_samples: 90000000
  use_dummy_dataloader: True

dataset_config:
  modality_config:
    image: True
    audio: True
    video: True
    text: True
    name: debug-v.${datamodule.dataset_config.modality_config.video}-a.${datamodule.dataset_config.modality_config.audio}-t.${datamodule.dataset_config.modality_config.text}-i.${datamodule.dataset_config.modality_config.image}
