_target_: tali.datasets.hub.TALIDataModule
config:
  dataset_root: ${data_dir}
  dataset_size_identifier: base
  dataset_name: ${datamodule.dataset_config.dataset_size_identifier}-tali
  modality_config:
    image: true
    audio: true
    video: true
    text: true
    name: video-${datamodule.dataset_config.modality_config.video}-audio-${datamodule.dataset_config.modality_config.audio}-text-${datamodule.dataset_config.modality_config.text}-image-${datamodule.dataset_config.modality_config.image}
  rescan_paths: False
  num_video_frames_per_datapoint: 80
  num_audio_frames_per_datapoint: 441000
  num_audio_sample_rate: 44100
  image_shape:
    channels: 3
    width: 360
    height: 180
  text_context_length: 77
batch_size: ${batch_size}
persistent_workers: true
pin_memory: True
prefetch_factor: 4
num_workers: 2
shuffle_train: True
shuffle_eval: True
train_start_index: 0
val_start_index: 0
test_start_index: 0