
_target_: capit.models.auto_builder.transformers.AutoCLIPTextTransformer
config:
  transformer_num_layers: 12
  transformer_num_heads: 8
  vocab_size: 49408
  context_length: 77
  embedding_output_features: 512
