_target_: tali.models.auto_builder.transformers.AutoConv1DTransformers
config:
  embedding_output_features: 512
  resnet_num_filters: 128
  resnet_num_stages: 3
  resnet_num_blocks: 0
  resnet_kernel_size: 7
  grid_patch_size: 16
  resnet_dilated: false
  transformer_num_layers: 12
  transformer_num_heads: 8
